#!/usr/bin/env php
<?php
foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        /** @noinspection PhpIncludeInspection */
        require $file;
        break;
    }
}

$factory = new Gitlab\Composer();

echo $factory->doStuff("lllllllllll");
echo "\n";
